---
development:
  adapter: mysql
  encoding: utf8
  database: website
  username: root
  password: ""
test:
  adapter: mysql2
  encoding: utf8
  database: db_46572014n3
  username: user46572014n3
  password: 5acuEjdn
  host: ny.railshoster.de
production:
  adapter: mysql
  encoding: utf8
  database: db_46572014n2
  username: user46572014n2
  password: "freakyceviin"
  host: ny.railshoster.de