development:
  encoding: utf8
  adapter: mysql2
  username: root
  host: localhost
  database: website
  password: 
test:
  encoding: utf8
  adapter: mysql2
  username: root
  host: localhost
  database: website_test
  password: 

