---
development:
  adapter: mysql
  encoding: utf8
  database: website
  username: root
  password: ""
test:
  adapter: mysql2
  encoding: utf8
  database: website
  username: root
  password: ""

production:
  adapter: mysql
  encoding: utf8
  database: db_46572014n2
  username: user46572014n2
  password: Z6SqXpuw
  
